package linsolve.functional;

import linsolve.Constraint;
import linsolve.LinearSolver;
import linsolve.LinearSpec;
import linsolve.OperatorType;
import linsolve.Variable;

public class LinearProblemsCollection {
	public static LinearSpec problem1(LinearSolver solver){
		LinearSpec ls = new LinearSpec(solver);
		Variable x5 = ls.addVariable("X5");
		Variable right = ls.addVariable("right");
		Variable top = ls.addVariable("top");
		Variable bottom = ls.addVariable("bottom");
		Variable left = ls.addVariable("left");
		Variable y6 = ls.addVariable("Y6");
		Variable x7 = ls.addVariable("X7");
		
		ls.addConstraint(-1, x5, 1,right, OperatorType.GE, 0.0d);
		ls.addConstraint(-1, top, 1, bottom, OperatorType.GE, 0.0d);
		ls.addConstraint(-1, left, 1, x5,  OperatorType.GE, 0.0d);
		ls.addConstraint(-1, y6, 1, bottom, OperatorType.GE, 0.0d);
		ls.addConstraint(-1, left, 1, x7, OperatorType.GE, 0.0d);
		ls.addConstraint(-1, top, 1, y6, OperatorType.GE, 0.0d);
		ls.addConstraint(-1, x7, 1, x5, OperatorType.GE, 0.0d);
		ls.addConstraint(-1, top, 1, y6, OperatorType.GE, 0.0d);
		ls.addConstraint(-1, left, 1, x7, OperatorType.EQ, 84.0d);
		ls.addConstraint(-1, y6, 1, bottom, OperatorType.EQ, 24.0d);
		ls.addConstraint(-1, top, 1, bottom, OperatorType.EQ, 88.0d);
		ls.addConstraint(-1, x7, 1, x5, OperatorType.EQ, 71.0d);
		ls.addConstraint(-1, top, 1, y6, OperatorType.EQ, 21.0d);
		ls.addConstraint(1, left, OperatorType.EQ, 0.0d);
		ls.addConstraint(1, top, OperatorType.EQ, 0.0d);
		ls.addConstraint(-1, left, 1, x5, OperatorType.EQ, 53.0d);
		ls.addConstraint(-1, x5, 1, right, OperatorType.EQ, 23.0d);
		ls.addConstraint(-1, top, 1, y6, OperatorType.EQ, 55.0d);
		
		return ls;
	}
	
	/**
	 * 
	 *  1x_1 + 1x_2 + 1x_3 = 5 (100)
	 *  1x_1 + 1x_2 + 1x_3 = 5 (50)
	 *  1x_1 + 1x_2 + 1x_3 = 5 (20)
	 * 
	 * @param solver
	 * @return
	 */
	public static LinearSpec problem2(LinearSolver solver){
		Constraint c;
		LinearSpec ls = new LinearSpec(solver);
		Variable x1 = ls.addVariable("x1");
		Variable x2 = ls.addVariable("x2");
		Variable x3 = ls.addVariable("x3");
		c = ls.addConstraint(1, x1, 1, x2, 1,x3, OperatorType.EQ, 5);
		c.setPenalty(100.0d);
		c = ls.addConstraint(1, x1, 1, x2, 1,x3, OperatorType.EQ, 10);
		c.setPenalty(50.0d);
		c = ls.addConstraint(1, x1, 1, x2, 1,x3, OperatorType.EQ, 15);
		c.setPenalty(20.0d);
		
		return ls;
	}
	
	public static LinearSpec problem3(LinearSolver solver){
		LinearSpec ls = new LinearSpec(solver);
		Variable left = ls.addVariable("left");
		Variable top = ls.addVariable("top");
		Variable right = ls.addVariable("right");
		Variable y7 = ls.addVariable("Y7");
		Variable bottom = ls.addVariable("bottom");
		Variable x8 = ls.addVariable("x8");
		Variable x9 = ls.addVariable("x9");
		Variable y6 = ls.addVariable("y6");
		Variable y5 = ls.addVariable("y5");
		Variable y10 = ls.addVariable("y10");
		Variable y11 = ls.addVariable("y11");
		Variable x12 = ls.addVariable("x12");
		
		ls.addConstraint(1, left, OperatorType.EQ, 0.0d, 100.0);
		ls.addConstraint(1, top, OperatorType.EQ, 0.0d, 100.0);
		ls.addConstraint(-1, left, 1, right, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, y7, 1, bottom, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, left, 1, right, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, x8, 1, x9, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, y6, 1, y5, OperatorType.GE, 0.0d,Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, x9, 1, right, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, y6, 1, y5, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, left, 1, right, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);	
		ls.addConstraint(-1, top, 1, y10, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, left, 1, right, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, y10, 1, y6, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, top, 1, y10, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, left, 1, right, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, y5, 1, y11, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, left, 1, right, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, y11, 1, y7, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, left, 1, x12, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, y6, 1, y5, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, x12, 1, x8, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, y6, 1, y5, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, left, 1, right, OperatorType.EQ, 39.0d, 1.373136086e9);
		ls.addConstraint(-1, y7, 1, bottom, OperatorType.EQ, 44.0d, -4.66908554e8);
		ls.addConstraint(-1, x8, 1, x9, OperatorType.EQ, 61.0d, -2.051880908e9);
		ls.addConstraint(-1, y6, 1, y5, OperatorType.EQ, 50.0d, -1.090075765e9);
		ls.addConstraint(-1, x9, 1, right, OperatorType.EQ, 26.0d, -1.30518524e9);
		ls.addConstraint(-1, y6, 1, y5, OperatorType.EQ, 39.0d, -1.101153639e9);
		ls.addConstraint(-1, left, 1, right, OperatorType.EQ, 87.0d, -1.76918059e8);
		ls.addConstraint(-1, top, 1, y10, OperatorType.EQ, 40.0d, 1.572672608e9);
		ls.addConstraint(-1, left, 1, right, OperatorType.EQ, 19.0d, 1.01355295e8);
		ls.addConstraint(-1, y10, 1, y6, OperatorType.EQ, 88.0d, 1.950237111e9);
		ls.addConstraint(-1, left, 1, right, OperatorType.EQ, 45.0d, 2.24716089e8);
		ls.addConstraint(-1, y5, 1, y11, OperatorType.EQ, 83.0d, 1.783284876e9);		
		ls.addConstraint(-1, left, 1, right, OperatorType.EQ, 91.0d, -7.74458244e8);
		ls.addConstraint(-1, y11, 1, y7, OperatorType.EQ, 28.0d, -8.5966551e7);
		ls.addConstraint(-1, left, 1, x12, OperatorType.EQ, 43.0d, 1.503177082e9);
		ls.addConstraint(-1, y6, 1, y5, OperatorType.EQ, 67.0d, -5.50641736e8);
		ls.addConstraint(-1, x12, 1, x8, OperatorType.EQ, 83.0d, 4.8226131e7);
		ls.addConstraint(-1, y6, 1, y5, OperatorType.EQ, 34.0d, -1.175993847e9);

		return ls;
	}
	
	
	public static LinearSpec problem4(LinearSolver solver){
		LinearSpec ls = new LinearSpec(solver);
		Variable left = ls.addVariable("left");
		Variable right = ls.addVariable("right");
		Variable top = ls.addVariable("top");
		Variable x6 = ls.addVariable("x6");
		Variable bottom = ls.addVariable("bottom");
		Variable y5 = ls.addVariable("y5");
		
		ls.addConstraint(-1, left, 1, right, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, top, 1, y5, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, left, 1, x6, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, y5, 1, bottom, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, x6, 1, right, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		//ls.addConstraint(-1, y5, 1, bottom, OperatorType.GE, 0.0d, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, y5, 1, bottom, OperatorType.EQ, 92.0d, 2.088469028e9);
		ls.addConstraint(-1, left, 1, right, OperatorType.EQ, 16.0d, 7.93310972e8);
		ls.addConstraint(-1, left, 1, x6, OperatorType.EQ, 54.0d, 6.91675816e8);
		ls.addConstraint(-1, y5, 1, bottom, OperatorType.EQ, 64.0d, 5.43635433e8);
		ls.addConstraint(-1, top, 1, y5, OperatorType.EQ, 87.0d, 5577367.0);
		ls.addConstraint(1, left, OperatorType.EQ, 0.0d, 100.0);
		ls.addConstraint(1, top, OperatorType.EQ, 0.0d, 100.0);
		ls.addConstraint(-1, x6, 1, right, OperatorType.EQ, 41.0d, -1.973979577e9);

		return ls;
	}

	// Constraints generated by Test1App.
	public static LinearSpec Test1App(LinearSolver solver){
		LinearSpec ls = new LinearSpec(solver);
		
		Variable left = ls.addVariable("left");
		Variable top = ls.addVariable("top");
		Variable right = ls.addVariable("right");
		Variable bottom = ls.addVariable("bottom");
		Variable X9 = ls.addVariable("X9");
		Variable Y10 = ls.addVariable("Y10");
		Variable Y11 = ls.addVariable("Y11");
		Variable Y12 = ls.addVariable("Y12");
		Variable Y13 = ls.addVariable("Y13");
		Variable X14 = ls.addVariable("X14");
		Variable X15 = ls.addVariable("X15");
		Variable X16 = ls.addVariable("X16");
		Variable Y17 = ls.addVariable("Y17");
		Variable Y18 = ls.addVariable("Y18");
		Variable Y19 = ls.addVariable("Y19");
		Variable Y20 = ls.addVariable("Y20");
		Variable X21 = ls.addVariable("X21");
		Variable X22 = ls.addVariable("X22");
		Variable X23 = ls.addVariable("X23");
		Variable X24 = ls.addVariable("X24");
		Variable Y25 = ls.addVariable("Y25");
		Variable Y26 = ls.addVariable("Y26");
		Variable Y27 = ls.addVariable("Y27");
		Variable Y28 = ls.addVariable("Y28");
		Variable X29 = ls.addVariable("X29");
		Variable X30 = ls.addVariable("X30");
		Variable X31 = ls.addVariable("X31");
		Variable X32 = ls.addVariable("X32");
		Variable X37 = ls.addVariable("X37");
		Variable X38 = ls.addVariable("X38");
		Variable X39 = ls.addVariable("X39");
		Variable Y40 = ls.addVariable("Y40");
		Variable Y41 = ls.addVariable("Y41");
		Variable Y42 = ls.addVariable("Y42");
		Variable Y43 = ls.addVariable("Y43");
		Variable X44 = ls.addVariable("X44");
		Variable X45 = ls.addVariable("X45");
		Variable X46 = ls.addVariable("X46");
		Variable X47 = ls.addVariable("X47");
		Variable Y48 = ls.addVariable("Y48");
		Variable Y49 = ls.addVariable("Y49");
		Variable Y50 = ls.addVariable("Y50");
		Variable Y51 = ls.addVariable("Y51");
		Variable X52 = ls.addVariable("X52");
		Variable X53 = ls.addVariable("X53");
		Variable X54 = ls.addVariable("X54");
		Variable X55 = ls.addVariable("X55");
		Variable X60 = ls.addVariable("X60");
		Variable X61 = ls.addVariable("X61");
		Variable X62 = ls.addVariable("X62");
		Variable Y63 = ls.addVariable("Y63");
		Variable Y64 = ls.addVariable("Y64");
		Variable Y65 = ls.addVariable("Y65");
		Variable Y66 = ls.addVariable("Y66");
		Variable X67 = ls.addVariable("X67");
		Variable X68 = ls.addVariable("X68");
		Variable X69 = ls.addVariable("X69");
		Variable X70 = ls.addVariable("X70");
		Variable Y71 = ls.addVariable("Y71");
		Variable Y72 = ls.addVariable("Y72");
		Variable Y73 = ls.addVariable("Y73");
		Variable Y74 = ls.addVariable("Y74");
		Variable X75 = ls.addVariable("X75");
		Variable X76 = ls.addVariable("X76");
		Variable X77 = ls.addVariable("X77");
		Variable X78 = ls.addVariable("X78");
		Variable Y83 = ls.addVariable("Y83");
		Variable Y84 = ls.addVariable("Y84");
		Variable Y85 = ls.addVariable("Y85");
		Variable X86 = ls.addVariable("X86");
		Variable X87 = ls.addVariable("X87");
		Variable Y88 = ls.addVariable("Y88");
		Variable Y89 = ls.addVariable("Y89");
		Variable Y90 = ls.addVariable("Y90");
		Variable Y91 = ls.addVariable("Y91");
		Variable X92 = ls.addVariable("X92");
		Variable X93 = ls.addVariable("X93");
		Variable X94 = ls.addVariable("X94");
		Variable X95 = ls.addVariable("X95");
		Variable Y96 = ls.addVariable("Y96");
		Variable Y97 = ls.addVariable("Y97");
		Variable Y98 = ls.addVariable("Y98");
		Variable Y99 = ls.addVariable("Y99");
		Variable X100 = ls.addVariable("X100");
		Variable X101 = ls.addVariable("X101");
		Variable X102 = ls.addVariable("X102");
		Variable X103 = ls.addVariable("X103");
		Variable Y108 = ls.addVariable("Y108");
		Variable Y109 = ls.addVariable("Y109");
		Variable Y110 = ls.addVariable("Y110");
		Variable X111 = ls.addVariable("X111");
		Variable X112 = ls.addVariable("X112");
		Variable Y113 = ls.addVariable("Y113");
		Variable Y114 = ls.addVariable("Y114");
		Variable Y115 = ls.addVariable("Y115");
		Variable Y116 = ls.addVariable("Y116");
		Variable X117 = ls.addVariable("X117");
		Variable X118 = ls.addVariable("X118");
		Variable X119 = ls.addVariable("X119");
		Variable X120 = ls.addVariable("X120");
		Variable Y121 = ls.addVariable("Y121");
		Variable Y122 = ls.addVariable("Y122");
		Variable Y123 = ls.addVariable("Y123");
		Variable Y124 = ls.addVariable("Y124");
		Variable X125 = ls.addVariable("X125");
		Variable X126 = ls.addVariable("X126");
		Variable X127 = ls.addVariable("X127");
		Variable X128 = ls.addVariable("X128");
		
		ls.addConstraint(1, left, OperatorType.EQ, 0.0, 100.0);
		ls.addConstraint(1, top, OperatorType.EQ, 0.0, 100.0);
		ls.addConstraint(-1, left, 1, X9, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X9, 1, right, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, top, 1, Y10, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y10, 1, bottom, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y10, 1, Y11, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y11, 1, bottom, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y12, -1, Y10, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y13, -1, Y11, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X9, 1, X14, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X14, 1, right, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X15, -1, X9, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X16, -1, X14, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y17, -1, Y12, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y13, -1, Y18, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y19, -1, Y17, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y20, -1, Y18, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X21, -1, X15, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X16, -1, X22, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X23, -1, X21, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X24, -1, X22, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y26, -1, Y25, OperatorType.GE, 26.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y27, -1, Y25, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y28, -1, Y26, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y27, -1, Y19, -1, Y20, 1, Y28, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y27, -1, Y19, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y20, -1, Y28, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X30, -1, X29, OperatorType.GE, 81.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X31, -1, X29, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X32, -1, X30, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X31, -1, X23, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X32, -1, X24, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X31, -1, X23, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X24, -1, X32, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X31, 1, X32, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y27, 1, Y28, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X31, 1, X32, OperatorType.EQ, 81.0, 3.0);
		ls.addConstraint(-1, Y27, 1, Y28, OperatorType.EQ, 26.0, 3.0);
		ls.addConstraint(-1, X14, 1, X37, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X37, 1, right, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X38, -1, X14, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X39, -1, X37, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y40, -1, Y12, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y13, -1, Y41, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y42, -1, Y40, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y43, -1, Y41, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X44, -1, X38, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X39, -1, X45, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X46, -1, X44, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X47, -1, X45, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y49, -1, Y48, OperatorType.GE, 26.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y50, -1, Y48, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y51, -1, Y49, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y50, -1, Y42, -1, Y43, 1, Y51, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y50, -1, Y42, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y43, -1, Y51, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X53, -1, X52, OperatorType.GE, 81.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X54, -1, X52, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X55, -1, X53, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X54, -1, X46, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X55, -1, X47, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X54, -1, X46, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X47, -1, X55, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X54, 1, X55, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y50, 1, Y51, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X54, 1, X55, OperatorType.EQ, 81.0, 3.0);
		ls.addConstraint(-1, Y50, 1, Y51, OperatorType.EQ, 26.0, 3.0);
		ls.addConstraint(-1, X37, 1, X60, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X60, 1, right, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X61, -1, X37, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X62, -1, X60, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y63, -1, Y12, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y13, -1, Y64, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y65, -1, Y63, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y66, -1, Y64, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X67, -1, X61, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X62, -1, X68, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X69, -1, X67, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X70, -1, X68, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y72, -1, Y71, OperatorType.GE, 26.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y73, -1, Y71, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y74, -1, Y72, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y73, -1, Y65, -1, Y66, 1, Y74, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y73, -1, Y65, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y66, -1, Y74, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X76, -1, X75, OperatorType.GE, 81.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X77, -1, X75, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X78, -1, X76, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X77, -1, X69, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X78, -1, X70, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X77, -1, X69, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X70, -1, X78, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X77, 1, X78, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y73, 1, Y74, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X77, 1, X78, OperatorType.EQ, 81.0, 3.0);
		ls.addConstraint(-1, Y73, 1, Y74, OperatorType.EQ, 26.0, 3.0);
		ls.addConstraint(-1, Y11, 1, Y83, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y83, 1, bottom, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y84, -1, Y11, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y85, -1, Y83, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X86, -1, X9, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X87, -1, X60, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y88, -1, Y84, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y85, -1, Y89, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y90, -1, Y88, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y91, -1, Y89, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X92, -1, X86, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X87, -1, X93, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X94, -1, X92, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X95, -1, X93, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y97, -1, Y96, OperatorType.GE, 66.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y98, -1, Y96, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y99, -1, Y97, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y98, -1, Y90, -1, Y91, 1, Y99, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y98, -1, Y90, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y91, -1, Y99, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X101, -1, X100, OperatorType.GE, 156.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X102, -1, X100, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X103, -1, X101, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X102, -1, X94, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X103, -1, X95, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X102, -1, X94, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X95, -1, X103, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X102, 1, X103, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y98, 1, Y99, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X102, 1, X103, OperatorType.EQ, 156.0, 3.0);
		ls.addConstraint(-1, Y98, 1, Y99, OperatorType.EQ, 26.0, 3.0);
		ls.addConstraint(-1, Y83, 1, Y108, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y108, 1, bottom, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y109, -1, Y83, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y110, -1, Y108, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X111, -1, X14, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X112, -1, X60, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y113, -1, Y109, OperatorType.EQ, 10.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y110, -1, Y114, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y115, -1, Y113, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y116, -1, Y114, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X117, -1, X111, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X112, -1, X118, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X119, -1, X117, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X120, -1, X118, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y122, -1, Y121, OperatorType.GE, 26.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y123, -1, Y121, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y124, -1, Y122, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y124, -1, Y116, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y123, -1, Y115, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y116, -1, Y124, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X126, -1, X125, OperatorType.GE, 41.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X127, -1, X125, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X128, -1, X126, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X127, -1, X119, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X128, -1, X120, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X127, -1, X119, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X120, -1, X128, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X127, 1, X128, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y123, 1, Y124, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X127, 1, X128, OperatorType.EQ, 41.0, 3.0);
		ls.addConstraint(-1, Y123, 1, Y124, OperatorType.EQ, 26.0, 3.0);
		ls.addConstraint(1, X9, -1, left, -1, right, 1, X60, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y10, -1, top, -1, bottom, 1, Y108, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, right, OperatorType.EQ, 484.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, bottom, OperatorType.EQ, 462.0, Double.POSITIVE_INFINITY);
		
		return ls;
	}

	// Constraints generated by Test4App.
	public static LinearSpec Test4App(LinearSolver solver){
		LinearSpec ls = new LinearSpec(solver);

		Variable left = ls.addVariable("left");
		Variable top = ls.addVariable("top");
		Variable right = ls.addVariable("right");
		Variable bottom = ls.addVariable("bottom");
		Variable X9 = ls.addVariable("X9");
		Variable Y10 = ls.addVariable("Y10");
		Variable Y11 = ls.addVariable("Y11");
		Variable Y12 = ls.addVariable("Y12");
		Variable Y13 = ls.addVariable("Y13");
		Variable X14 = ls.addVariable("X14");
		Variable X15 = ls.addVariable("X15");
		Variable X16 = ls.addVariable("X16");
		Variable Y17 = ls.addVariable("Y17");
		Variable Y18 = ls.addVariable("Y18");
		Variable Y19 = ls.addVariable("Y19");
		Variable Y20 = ls.addVariable("Y20");
		Variable X21 = ls.addVariable("X21");
		Variable X22 = ls.addVariable("X22");
		Variable X23 = ls.addVariable("X23");
		Variable X24 = ls.addVariable("X24");
		Variable Y25 = ls.addVariable("Y25");
		Variable Y26 = ls.addVariable("Y26");
		Variable Y27 = ls.addVariable("Y27");
		Variable Y28 = ls.addVariable("Y28");
		Variable X29 = ls.addVariable("X29");
		Variable X30 = ls.addVariable("X30");
		Variable X31 = ls.addVariable("X31");
		Variable X32 = ls.addVariable("X32");
		Variable X37 = ls.addVariable("X37");
		Variable X38 = ls.addVariable("X38");
		Variable X39 = ls.addVariable("X39");
		Variable Y40 = ls.addVariable("Y40");
		Variable Y41 = ls.addVariable("Y41");
		Variable Y42 = ls.addVariable("Y42");
		Variable Y43 = ls.addVariable("Y43");
		Variable X44 = ls.addVariable("X44");
		Variable X45 = ls.addVariable("X45");
		Variable X46 = ls.addVariable("X46");
		Variable X47 = ls.addVariable("X47");
		Variable Y48 = ls.addVariable("Y48");
		Variable Y49 = ls.addVariable("Y49");
		Variable Y50 = ls.addVariable("Y50");
		Variable Y51 = ls.addVariable("Y51");
		Variable X52 = ls.addVariable("X52");
		Variable X53 = ls.addVariable("X53");
		Variable X54 = ls.addVariable("X54");
		Variable X55 = ls.addVariable("X55");
		Variable Y60 = ls.addVariable("Y60");
		Variable Y61 = ls.addVariable("Y61");
		Variable Y62 = ls.addVariable("Y62");
		Variable Y63 = ls.addVariable("Y63");
		Variable Y64 = ls.addVariable("Y64");
		Variable Y65 = ls.addVariable("Y65");
		Variable Y66 = ls.addVariable("Y66");
		Variable X67 = ls.addVariable("X67");
		Variable X68 = ls.addVariable("X68");
		Variable X69 = ls.addVariable("X69");
		Variable X70 = ls.addVariable("X70");
		Variable Y71 = ls.addVariable("Y71");
		Variable Y72 = ls.addVariable("Y72");
		Variable Y73 = ls.addVariable("Y73");
		Variable Y74 = ls.addVariable("Y74");
		Variable X75 = ls.addVariable("X75");
		Variable X76 = ls.addVariable("X76");
		Variable X77 = ls.addVariable("X77");
		Variable X78 = ls.addVariable("X78");
		Variable Y83 = ls.addVariable("Y83");
		Variable Y84 = ls.addVariable("Y84");
		Variable Y85 = ls.addVariable("Y85");
		Variable Y86 = ls.addVariable("Y86");
		Variable X87 = ls.addVariable("X87");
		Variable X88 = ls.addVariable("X88");
		Variable X89 = ls.addVariable("X89");
		Variable X90 = ls.addVariable("X90");
		Variable Y91 = ls.addVariable("Y91");
		Variable Y92 = ls.addVariable("Y92");
		Variable Y93 = ls.addVariable("Y93");
		Variable Y94 = ls.addVariable("Y94");
		Variable X95 = ls.addVariable("X95");
		Variable X96 = ls.addVariable("X96");
		Variable X97 = ls.addVariable("X97");
		Variable X98 = ls.addVariable("X98");

		ls.addConstraint(1, left, OperatorType.EQ, 0.0, 100.0);
		ls.addConstraint(1, top, OperatorType.EQ, 0.0, 100.0);
		ls.addConstraint(-1, left, 1, X9, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X9, 1, right, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, top, 1, Y10, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y10, 1, bottom, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y10, 1, Y11, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y11, 1, bottom, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y12, -1, Y10, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y13, -1, Y11, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X9, 1, X14, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X14, 1, right, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X15, -1, X9, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X16, -1, X14, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y17, -1, Y12, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y13, -1, Y18, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y19, -1, Y17, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y20, -1, Y18, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X21, -1, X15, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X16, -1, X22, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X23, -1, X21, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X24, -1, X22, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y26, -1, Y25, OperatorType.GE, 26.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y27, -1, Y25, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y28, -1, Y26, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y27, -1, Y19, -1, Y20, 1, Y28, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y27, -1, Y19, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y20, -1, Y28, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X30, -1, X29, OperatorType.GE, 77.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X31, -1, X29, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X32, -1, X30, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X31, -1, X23, -1, X24, 1, X32, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X31, -1, X23, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X24, -1, X32, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X31, 1, X32, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y27, 1, Y28, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X31, 1, X32, OperatorType.EQ, 77.0, 3.0);
		ls.addConstraint(-1, Y27, 1, Y28, OperatorType.EQ, 26.0, 3.0);
		ls.addConstraint(-1, X14, 1, X37, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X37, 1, right, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X38, -1, X14, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X39, -1, X37, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y40, -1, Y12, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y13, -1, Y41, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y42, -1, Y40, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y43, -1, Y41, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X44, -1, X38, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X39, -1, X45, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X46, -1, X44, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X47, -1, X45, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y49, -1, Y48, OperatorType.GE, 26.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y50, -1, Y48, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y51, -1, Y49, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y50, -1, Y42, -1, Y43, 1, Y51, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y50, -1, Y42, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y43, -1, Y51, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X53, -1, X52, OperatorType.GE, 77.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X54, -1, X52, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X55, -1, X53, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X54, -1, X46, -1, X47, 1, X55, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X54, -1, X46, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X47, -1, X55, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X54, 1, X55, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y50, 1, Y51, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X54, 1, X55, OperatorType.EQ, 77.0, 3.0);
		ls.addConstraint(-1, Y50, 1, Y51, OperatorType.EQ, 26.0, 3.0);
		ls.addConstraint(-1, Y11, 1, Y60, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y60, 1, bottom, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y61, -1, Y11, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y62, -1, Y60, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y63, -1, Y61, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y62, -1, Y64, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y65, -1, Y63, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y66, -1, Y64, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X67, -1, X15, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X16, -1, X68, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X69, -1, X67, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X70, -1, X68, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y72, -1, Y71, OperatorType.GE, 26.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y73, -1, Y71, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y74, -1, Y72, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y73, -1, Y65, -1, Y66, 1, Y74, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y73, -1, Y65, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y66, -1, Y74, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X76, -1, X75, OperatorType.GE, 77.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X77, -1, X75, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X78, -1, X76, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X77, -1, X69, -1, X70, 1, X78, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X77, -1, X69, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X70, -1, X78, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X77, 1, X78, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y73, 1, Y74, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X77, 1, X78, OperatorType.EQ, 77.0, 3.0);
		ls.addConstraint(-1, Y73, 1, Y74, OperatorType.EQ, 26.0, 3.0);
		ls.addConstraint(1, Y83, -1, Y61, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y62, -1, Y84, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y85, -1, Y83, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y86, -1, Y84, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X87, -1, X38, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X39, -1, X88, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X89, -1, X87, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X90, -1, X88, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y92, -1, Y91, OperatorType.GE, 26.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y93, -1, Y91, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y94, -1, Y92, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y93, -1, Y85, -1, Y86, 1, Y94, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y93, -1, Y85, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y86, -1, Y94, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X96, -1, X95, OperatorType.GE, 77.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X97, -1, X95, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X98, -1, X96, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X97, -1, X89, -1, X90, 1, X98, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X97, -1, X89, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X90, -1, X98, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X97, 1, X98, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y93, 1, Y94, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X97, 1, X98, OperatorType.EQ, 77.0, 3.0);
		ls.addConstraint(-1, Y93, 1, Y94, OperatorType.EQ, 26.0, 3.0);
		ls.addConstraint(1, X9, -1, left, -1, right, 1, X37, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y10, -1, top, -1, bottom, 1, Y60, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, right, OperatorType.EQ, 484.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, bottom, OperatorType.EQ, 462.0, Double.POSITIVE_INFINITY);

		return ls;
}

	
	// Constraints generated by ThreeButtons
	public static LinearSpec ThreeButtons(LinearSolver solver){
		LinearSpec ls = new LinearSpec(solver);

		Variable left = ls.addVariable("left");
		Variable top = ls.addVariable("top");
		Variable right = ls.addVariable("right");
		Variable bottom = ls.addVariable("bottom");
		Variable x1 = ls.addVariable("x1");
		Variable y1 = ls.addVariable("y1");
		
		ls.addConstraint(1, left, OperatorType.EQ, 0.0, 100);
		ls.addConstraint(1, top, OperatorType.EQ, 0.0, 100);
		ls.addConstraint(-1, left, 1, x1, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, top, 1, y1, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, left, 1, x1, OperatorType.EQ, 77.0, 3.0);
		ls.addConstraint(-1, top, 1, y1, OperatorType.EQ, 26.0, 3.0);
		ls.addConstraint(-1, x1, 1, right, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, top, 1, y1, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, x1, 1, right, OperatorType.EQ, 77.0, 3.0);
		ls.addConstraint(-1, top, 1, y1, OperatorType.EQ, 26.0, 3.0);
		ls.addConstraint(-1, left, 1, right, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, y1, 1, bottom, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, left, 1, right, OperatorType.EQ, 77.0, 3.0);
		ls.addConstraint(-1, y1, 1, bottom, OperatorType.EQ, 26.0, 3.0);
		ls.addConstraint(2, x1, -1, right, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(2, y1, -1, bottom, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, right, OperatorType.EQ, 276.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, bottom, OperatorType.EQ, 228.0, Double.POSITIVE_INFINITY);
		
		return ls;
	}

	public static LinearSpec ThirteenWidgets(LinearSolver solver){
		LinearSpec ls = new LinearSpec(solver);
		
		Variable left = ls.addVariable("left");
		Variable top = ls.addVariable("top");
		Variable right = ls.addVariable("right");
		Variable bottom = ls.addVariable("bottom");
		Variable X9 = ls.addVariable("X9");
		Variable X10 = ls.addVariable("X10");
		Variable X11 = ls.addVariable("X11");
		Variable Y12 = ls.addVariable("Y12");
		Variable Y13 = ls.addVariable("Y13");
		Variable Y14 = ls.addVariable("Y14");
		Variable Y15 = ls.addVariable("Y15");
		Variable Y16 = ls.addVariable("Y16");
		Variable X61 = ls.addVariable("X61");
		Variable Y62 = ls.addVariable("Y62");
		Variable X63 = ls.addVariable("X63");
		Variable Y64 = ls.addVariable("Y64");
		Variable X69 = ls.addVariable("X69");
		Variable Y70 = ls.addVariable("Y70");
		Variable X71 = ls.addVariable("X71");
		Variable Y72 = ls.addVariable("Y72");
		Variable X77 = ls.addVariable("X77");
		Variable Y78 = ls.addVariable("Y78");
		Variable X79 = ls.addVariable("X79");
		Variable Y80 = ls.addVariable("Y80");
		Variable X85 = ls.addVariable("X85");
		Variable Y86 = ls.addVariable("Y86");
		Variable X87 = ls.addVariable("X87");
		Variable Y88 = ls.addVariable("Y88");
		
		ls.addConstraint(1, left, OperatorType.EQ, 0.0, 100.0);
		ls.addConstraint(1, top, OperatorType.EQ, 0.0, 100.0);
		ls.addConstraint(-1, left, 1, X9, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, top, 1, Y12, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, left, 1, X9, OperatorType.EQ, 77.0, 3.0);
		ls.addConstraint(-1, top, 1, Y12, OperatorType.EQ, 26.0, 3.0);
		ls.addConstraint(-1, X9, 1, X10, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, top, 1, Y12, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X9, 1, X10, OperatorType.EQ, 77.0, 3.0);
		ls.addConstraint(-1, top, 1, Y12, OperatorType.EQ, 26.0, 3.0);
		ls.addConstraint(-1, left, 1, X9, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y12, 1, Y13, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, left, 1, X9, OperatorType.EQ, 77.0, 3.0);
		ls.addConstraint(-1, Y12, 1, Y13, OperatorType.EQ, 26.0, 3.0);
		ls.addConstraint(-1, X9, 1, X10, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y12, 1, Y13, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X9, 1, X10, OperatorType.EQ, 77.0, 3.0);
		ls.addConstraint(-1, Y12, 1, Y13, OperatorType.EQ, 26.0, 3.0);
		ls.addConstraint(-1, left, 1, X9, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y13, 1, Y14, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, left, 1, X9, OperatorType.EQ, 77.0, 3.0);
		ls.addConstraint(-1, Y13, 1, Y14, OperatorType.EQ, 26.0, 3.0);
		ls.addConstraint(-1, X9, 1, X10, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y13, 1, Y14, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X9, 1, X10, OperatorType.EQ, 77.0, 3.0);
		ls.addConstraint(-1, Y13, 1, Y14, OperatorType.EQ, 26.0, 3.0);
		ls.addConstraint(2, X9, -1, X10, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(2, Y12, -1, Y13, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y12, 1, Y13, -1, Y14, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, left, 1, X10, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y14, 1, Y15, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, left, 1, X10, OperatorType.EQ, 0.0, 1.0);
		ls.addConstraint(-1, Y14, 1, Y15, OperatorType.EQ, 0.0, 1.0);
		ls.addConstraint(-1, X10, 1, right, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, top, 1, Y13, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X10, 1, right, OperatorType.EQ, 45.0, 1.0);
		ls.addConstraint(-1, top, 1, Y13, OperatorType.EQ, 16.0, 1.0);
		ls.addConstraint(-1, left, 1, X11, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y15, 1, Y16, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, left, 1, X11, OperatorType.EQ, 65.0, 1.0);
		ls.addConstraint(-1, Y15, 1, Y16, OperatorType.EQ, 23.0, 1.0);
		ls.addConstraint(-1, X11, 1, right, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y13, 1, Y16, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X11, 1, right, OperatorType.EQ, 45.0, 1.0);
		ls.addConstraint(-1, Y13, 1, Y16, OperatorType.EQ, 16.0, 1.0);
		ls.addConstraint(-1, X61, 1, X63, OperatorType.EQ, 69.0, 1.0);
		ls.addConstraint(-1, Y62, 1, Y64, OperatorType.EQ, 16.0, 1.0);
		ls.addConstraint(-1, X61, 1, X63, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y62, 1, Y64, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X10, 1, X61, OperatorType.EQ, 10.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y13, 1, Y62, OperatorType.EQ, 10.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X63, 1, X11, OperatorType.EQ, 10.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y64, 1, Y15, OperatorType.EQ, 10.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X69, 1, X71, OperatorType.EQ, 34.0, 3.0);
		ls.addConstraint(-1, Y70, 1, Y72, OperatorType.EQ, 16.0, 3.0);
		ls.addConstraint(-1, X69, 1, X71, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y70, 1, Y72, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, left, 1, X69, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y16, 1, Y70, OperatorType.EQ, 4.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X71, 1, X10, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y72, 1, bottom, OperatorType.EQ, 4.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X77, 1, X79, OperatorType.EQ, 34.0, 3.0);
		ls.addConstraint(-1, Y78, 1, Y80, OperatorType.EQ, 16.0, 3.0);
		ls.addConstraint(-1, X77, 1, X79, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y78, 1, Y80, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X10, 1, X77, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y16, 1, Y78, OperatorType.EQ, 4.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X10, 1, X77, 1, X79, -1, X11, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y80, 1, bottom, OperatorType.EQ, 4.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X85, 1, X87, OperatorType.EQ, 34.0, 3.0);
		ls.addConstraint(-1, Y86, 1, Y88, OperatorType.EQ, 16.0, 3.0);
		ls.addConstraint(-1, X85, 1, X87, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y86, 1, Y88, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X11, 1, X85, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y16, 1, Y86, OperatorType.EQ, 4.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X87, 1, right, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y88, 1, bottom, OperatorType.EQ, 4.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, right, OperatorType.EQ, 494.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, bottom, OperatorType.EQ, 318.0, Double.POSITIVE_INFINITY);
		
		return ls;
	}

	public static LinearSpec TableTest(LinearSolver solver){
		LinearSpec ls = new LinearSpec(solver);

		Variable left = ls.addVariable("left");
		Variable top = ls.addVariable("top");
		Variable right = ls.addVariable("right");
		Variable bottom = ls.addVariable("bottom");
		Variable X9 = ls.addVariable("X9");
		Variable X10 = ls.addVariable("X10");
		Variable Y11 = ls.addVariable("Y11");
		Variable Y12 = ls.addVariable("Y12");
		Variable Y13 = ls.addVariable("Y13");
		Variable Y14 = ls.addVariable("Y14");
		Variable Y15 = ls.addVariable("Y15");
		Variable Y16 = ls.addVariable("Y16");
		Variable X21 = ls.addVariable("X21");
		Variable Y22 = ls.addVariable("Y22");
		Variable X23 = ls.addVariable("X23");
		Variable Y24 = ls.addVariable("Y24");
		Variable X29 = ls.addVariable("X29");
		Variable Y30 = ls.addVariable("Y30");
		Variable X31 = ls.addVariable("X31");
		Variable Y32 = ls.addVariable("Y32");
		Variable X37 = ls.addVariable("X37");
		Variable Y38 = ls.addVariable("Y38");
		Variable X39 = ls.addVariable("X39");
		Variable Y40 = ls.addVariable("Y40");

		ls.addConstraint(1, left, OperatorType.EQ, 0.0, 100.0);
		ls.addConstraint(1, top, OperatorType.EQ, 0.0, 100.0);
		ls.addConstraint(1, X9, -1, left, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, X10, -1, right, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y11, -1, top, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y14, -1, bottom, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y16, -1, Y13, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, Y12, -1, Y15, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X21, 1, X23, OperatorType.EQ, 49.0, 3.0);
		ls.addConstraint(-1, Y22, 1, Y24, OperatorType.EQ, 26.0, 3.0);
		ls.addConstraint(-1, X21, 1, X23, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y22, 1, Y24, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X9, 1, X21, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y11, 1, Y22, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X23, 1, X10, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y24, 1, Y12, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X29, 1, X31, OperatorType.EQ, 49.0, 3.0);
		ls.addConstraint(-1, Y30, 1, Y32, OperatorType.EQ, 26.0, 3.0);
		ls.addConstraint(-1, X29, 1, X31, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y30, 1, Y32, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X9, 1, X29, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y15, 1, Y30, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X9, 1, X29, 1, X31, -1, X10, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y15, 1, Y30, 1, Y32, -1, Y16, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X37, 1, X39, OperatorType.EQ, 49.0, 3.0);
		ls.addConstraint(-1, Y38, 1, Y40, OperatorType.EQ, 26.0, 3.0);
		ls.addConstraint(-1, X37, 1, X39, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y38, 1, Y40, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X9, 1, X37, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y13, 1, Y38, OperatorType.GE, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, X39, 1, X10, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y40, 1, Y14, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y15, 1, Y16, 1, Y11, -1, Y12, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(-1, Y13, 1, Y14, 1, Y11, -1, Y12, OperatorType.EQ, 0.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, right, OperatorType.EQ, 284.0, Double.POSITIVE_INFINITY);
		ls.addConstraint(1, bottom, OperatorType.EQ, 262.0, Double.POSITIVE_INFINITY);

		return ls;
	}	
		
}
