//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.30 at 04:13:53 PM NZDT 
//


package jaxb;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="area" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="left" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="top" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="right" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="bottom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="leftinset" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="topinset" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="rightinset" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="bottominset" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="horizontalalignment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="verticalalignment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="constraint" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="leftside" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="summand" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="coeff" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                       &lt;element name="var" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="op" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="rightside" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="penaltyneg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="penaltypos" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "version",
    "area",
    "constraint"
})
@XmlRootElement(name = "almlayout")
public class ALMSchema {

    @XmlElement(required = true)
    protected BigInteger version;
    protected List<ALMSchema.Area> area;
    protected List<ALMSchema.Constraint> constraint;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersion(BigInteger value) {
        this.version = value;
    }

    /**
     * Gets the value of the area property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the area property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArea().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ALMSchema.Area }
     * 
     * 
     */
    public List<ALMSchema.Area> getArea() {
        if (area == null) {
            area = new ArrayList<ALMSchema.Area>();
        }
        return this.area;
    }

    /**
     * Gets the value of the constraint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the constraint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConstraint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ALMSchema.Constraint }
     * 
     * 
     */
    public List<ALMSchema.Constraint> getConstraint() {
        if (constraint == null) {
            constraint = new ArrayList<ALMSchema.Constraint>();
        }
        return this.constraint;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="left" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="top" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="right" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="bottom" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="leftinset" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="topinset" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="rightinset" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="bottominset" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="horizontalalignment" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="verticalalignment" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "left",
        "top",
        "right",
        "bottom",
        "leftinset",
        "topinset",
        "rightinset",
        "bottominset",
        "horizontalalignment",
        "verticalalignment"
    })
    public static class Area {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String left;
        @XmlElement(required = true)
        protected String top;
        @XmlElement(required = true)
        protected String right;
        @XmlElement(required = true)
        protected String bottom;
        @XmlElement(required = true)
        protected BigInteger leftinset;
        @XmlElement(required = true)
        protected BigInteger topinset;
        @XmlElement(required = true)
        protected BigInteger rightinset;
        @XmlElement(required = true)
        protected BigInteger bottominset;
        @XmlElement(required = true)
        protected String horizontalalignment;
        @XmlElement(required = true)
        protected String verticalalignment;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the left property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLeft() {
            return left;
        }

        /**
         * Sets the value of the left property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLeft(String value) {
            this.left = value;
        }

        /**
         * Gets the value of the top property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTop() {
            return top;
        }

        /**
         * Sets the value of the top property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTop(String value) {
            this.top = value;
        }

        /**
         * Gets the value of the right property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRight() {
            return right;
        }

        /**
         * Sets the value of the right property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRight(String value) {
            this.right = value;
        }

        /**
         * Gets the value of the bottom property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBottom() {
            return bottom;
        }

        /**
         * Sets the value of the bottom property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBottom(String value) {
            this.bottom = value;
        }

        /**
         * Gets the value of the leftinset property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getLeftinset() {
            return leftinset;
        }

        /**
         * Sets the value of the leftinset property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setLeftinset(BigInteger value) {
            this.leftinset = value;
        }

        /**
         * Gets the value of the topinset property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTopinset() {
            return topinset;
        }

        /**
         * Sets the value of the topinset property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTopinset(BigInteger value) {
            this.topinset = value;
        }

        /**
         * Gets the value of the rightinset property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getRightinset() {
            return rightinset;
        }

        /**
         * Sets the value of the rightinset property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setRightinset(BigInteger value) {
            this.rightinset = value;
        }

        /**
         * Gets the value of the bottominset property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getBottominset() {
            return bottominset;
        }

        /**
         * Sets the value of the bottominset property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setBottominset(BigInteger value) {
            this.bottominset = value;
        }

        /**
         * Gets the value of the horizontalalignment property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHorizontalalignment() {
            return horizontalalignment;
        }

        /**
         * Sets the value of the horizontalalignment property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHorizontalalignment(String value) {
            this.horizontalalignment = value;
        }

        /**
         * Gets the value of the verticalalignment property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVerticalalignment() {
            return verticalalignment;
        }

        /**
         * Sets the value of the verticalalignment property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVerticalalignment(String value) {
            this.verticalalignment = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="leftside" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="summand" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="coeff" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                             &lt;element name="var" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="op" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="rightside" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="penaltyneg" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="penaltypos" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "leftside",
        "op",
        "rightside",
        "penaltyneg",
        "penaltypos"
    })
    public static class Constraint {

        protected List<ALMSchema.Constraint.Leftside> leftside;
        @XmlElement(required = true)
        protected String op;
        @XmlElement(required = true)
        protected BigDecimal rightside;
        @XmlElement(required = true)
        protected String penaltyneg;
        @XmlElement(required = true)
        protected String penaltypos;

        /**
         * Gets the value of the leftside property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the leftside property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLeftside().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ALMSchema.Constraint.Leftside }
         * 
         * 
         */
        public List<ALMSchema.Constraint.Leftside> getLeftside() {
            if (leftside == null) {
                leftside = new ArrayList<ALMSchema.Constraint.Leftside>();
            }
            return this.leftside;
        }

        /**
         * Gets the value of the op property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOp() {
            return op;
        }

        /**
         * Sets the value of the op property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOp(String value) {
            this.op = value;
        }

        /**
         * Gets the value of the rightside property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getRightside() {
            return rightside;
        }

        /**
         * Sets the value of the rightside property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setRightside(BigDecimal value) {
            this.rightside = value;
        }

        /**
         * Gets the value of the penaltyneg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPenaltyneg() {
            return penaltyneg;
        }

        /**
         * Sets the value of the penaltyneg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPenaltyneg(String value) {
            this.penaltyneg = value;
        }

        /**
         * Gets the value of the penaltypos property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPenaltypos() {
            return penaltypos;
        }

        /**
         * Sets the value of the penaltypos property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPenaltypos(String value) {
            this.penaltypos = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="summand" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="coeff" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *                   &lt;element name="var" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "summand"
        })
        public static class Leftside {

            protected List<ALMSchema.Constraint.Leftside.Summand> summand;

            /**
             * Gets the value of the summand property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the summand property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSummand().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ALMSchema.Constraint.Leftside.Summand }
             * 
             * 
             */
            public List<ALMSchema.Constraint.Leftside.Summand> getSummand() {
                if (summand == null) {
                    summand = new ArrayList<ALMSchema.Constraint.Leftside.Summand>();
                }
                return this.summand;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="coeff" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             *         &lt;element name="var" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "coeff",
                "var",
                "type"
            })
            public static class Summand {

                @XmlElement(required = true)
                protected BigDecimal coeff;
                @XmlElement(required = true)
                protected String var;
                @XmlElement(required = true)
                protected String type;

                /**
                 * Gets the value of the coeff property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getCoeff() {
                    return coeff;
                }

                /**
                 * Sets the value of the coeff property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setCoeff(BigDecimal value) {
                    this.coeff = value;
                }

                /**
                 * Gets the value of the var property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVar() {
                    return var;
                }

                /**
                 * Sets the value of the var property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVar(String value) {
                    this.var = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

            }

        }

    }

}
