//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.30 at 04:13:53 PM NZDT 
//


package jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ALMSchema }
     * 
     */
    public ALMSchema createAlmlayout() {
        return new ALMSchema();
    }

    /**
     * Create an instance of {@link ALMSchema.Constraint }
     * 
     */
    public ALMSchema.Constraint createAlmlayoutConstraint() {
        return new ALMSchema.Constraint();
    }

    /**
     * Create an instance of {@link ALMSchema.Constraint.Leftside }
     * 
     */
    public ALMSchema.Constraint.Leftside createAlmlayoutConstraintLeftside() {
        return new ALMSchema.Constraint.Leftside();
    }

    /**
     * Create an instance of {@link ALMSchema.Area }
     * 
     */
    public ALMSchema.Area createAlmlayoutArea() {
        return new ALMSchema.Area();
    }

    /**
     * Create an instance of {@link ALMSchema.Constraint.Leftside.Summand }
     * 
     */
    public ALMSchema.Constraint.Leftside.Summand createAlmlayoutConstraintLeftsideSummand() {
        return new ALMSchema.Constraint.Leftside.Summand();
    }

}
